name: twist_moe
version: 0.0.1
author: Phani Rithvij
repository: https://github.com/phanirithvij/twist.moe

dependencies:
  path: ^1.6.4
  args: ^1.5.2
  crypto: ^2.1.4
  json_annotation: ^3.0.1
  pointycastle: ^1.0.2

dev_dependencies:
  build_runner: ^1.7.2
  json_serializable: ^3.2.5
